#########################
### build environment ###
#########################

# base image
FROM node:10.15.1-alpine as builder

# set working directory
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package*.json /usr/src/app/
COPY .npmrc /usr/src/app/
RUN npm install

# add app
COPY . /usr/src/app

# exposed port
EXPOSE 4200/tcp

# generate build
RUN npm run build

##################
### production ###
##################

# base image
FROM nginx:1.15.8-alpine

# copy artifact build from the 'build environment'
COPY --from=builder /usr/src/app/dist/web /usr/share/nginx/html

# copy the nginx.conf file
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# expose port 80
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]
